services:
  app:
    build:
      context: .
    ports:
      - '${PORT:-8000}:8000'
    deploy:
      resources:
        limits:
          memory: 512m
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'wsh24.trasta.dev -> http://app:8000'
      STAGE: 'production'
      FORCE_RENEW: 'false'
      CLIENT_MAX_BODY_SIZE: 0
    restart: unless-stopped
    volumes:
      - https-portal_data:/var/lib/https-portal
